# Generated by Django 2.0.4 on 2018-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_Name', models.CharField(max_length=30)),
                ('U_Email', models.CharField(max_length=30)),
                ('U_DOB', models.DateField()),
                ('U_Password', models.CharField(max_length=30)),
                ('U_Profile', models.CharField(max_length=200)),
            ],
        ),
    ]
