# Generated by Django 2.0.4 on 2018-05-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayNLearn', '0003_remove_user_u_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='U_Profile',
        ),
    ]
