# Generated by Django 2.0.4 on 2018-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayNLearn', '0004_remove_user_u_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='signUp',
        ),
    ]
